#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=96
USE_PROCD=1
PROG=/usr/bin/httpd

start_service() {
	procd_open_instance
	procd_set_param respawn 60 5 -1
	procd_set_param command "$PROG"
	procd_close_instance
}

reload() {
	killall $PROG
}
