#!/bin/sh /etc/rc.common
# Copyright (C) 2009 OpenWrt.org

START=99
USE_PROCD=1
PROG=/usr/bin/mswitchd

start_service() {
	procd_open_instance
	procd_set_param respawn 60 5 -1
	procd_set_param command "$PROG"
	procd_close_instance
}

reload() {
	killall $PROG
}
